apiVersion: v1
kind: Pod
metadata:
  name: ovs-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-ovs-net, userspace-ovs-net
spec:
  containers:
  - name: multi-vhost
    image: dpdk-app-centos:latest
    imagePullPolicy: IfNotPresent
    terminationMessagePath: "/tmp/ovs-pod/"
#    command: [ "/bin/bash", "-c", "--" ]
#    args: [ "while true; do sleep 30; done;" ]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podinfo
      readOnly: false
    - mountPath: /var/run/openvswitch/
      name: shared-dir
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 2Mi
        hugepages-1Gi: 1Gi
      limits:
        hugepages-1Gi: 1Gi
    command: ["sleep", "infinity"]
#  nodeSelector:
#    vswitch: ovs
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: shared-dir
    hostPath:
      path: /usr/local/var/run/openvswitch/
  - name: hugepage
    emptyDir:
      medium: HugePages
